//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rols
    {
        public int idTeacher { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string NameRole { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
