//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Exam1 = new HashSet<Exam1>();
        }
    
        public string NamberStudent { get; set; }
        public string LastName { get; set; }
        public string FerstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> Bithday { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PassportSeries { get; set; }
        public Nullable<int> PassportNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam1> Exam1 { get; set; }
        public virtual Studying Studying { get; set; }
    }
}
