//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSpec
    {
        public int IdSubject { get; set; }
        public string idTeacher { get; set; }
    
        public virtual Specialty Specialty { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
