//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.TS = new HashSet<TS>();
        }
    
        public int idTeacher { get; set; }
        public string LastName { get; set; }
        public string FerstName { get; set; }
        public string MiddleName { get; set; }
        public string Experience { get; set; }
        public string Discharge { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Bithday { get; set; }
    
        public virtual Rols Rols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS> TS { get; set; }
    }
}
