//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS
    {
        public int idTeacher { get; set; }
        public string Year { get; set; }
        public int idSubgect { get; set; }
        public string Salary { get; set; }
        public int Time { get; set; }
    
        public virtual Exam1 Exam1 { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
